export const indianStatesOptions = [
    { key: "Andhra Pradesh", value: "Andhra Pradesh" },
    { key: "Arunachal Pradesh", value: "Arunachal Pradesh" },
    { key: "Assam", value: "Assam" },
    { key: "Bihar", value: "Bihar" },
    { key: "Chhattisgarh", value: "Chhattisgarh" },
    { key: "Goa", value: "Goa" },
    { key: "Gujarat", value: "Gujarat" },
    { key: "Haryana", value: "Haryana" },
    { key: "Himachal Pradesh", value: "Himachal Pradesh" },
    { key: "Jharkhand", value: "Jharkhand" },
    { key: "Karnataka", value: "Karnataka" },
    { key: "Kerala", value: "Kerala" },
    { key: "Madhya Pradesh", value: "Madhya Pradesh" },
    { key: "Maharashtra", value: "Maharashtra" },
    { key: "Manipur", value: "Manipur" },
    { key: "Meghalaya", value: "Meghalaya" },
    { key: "Mizoram", value: "Mizoram" },
    { key: "Nagaland", value: "Nagaland" },
    { key: "Odisha", value: "Odisha" },
    { key: "Punjab", value: "Punjab" },
    { key: "Rajasthan", value: "Rajasthan" },
    { key: "Sikkim", value: "Sikkim" },
    { key: "Tamil Nadu", value: "Tamil Nadu" },
    { key: "Telangana", value: "Telangana" },
    { key: "Tripura", value: "Tripura" },
    { key: "Uttar Pradesh", value: "Uttar Pradesh" },
    { key: "Uttarakhand", value: "Uttarakhand" },
    { key: "West Bengal", value: "West Bengal" },
  ];
  